export const categories = [
  {
    title: "외장 옵션",
    options: [
      { name: "제논라이트(HID)", image: "/Image/options/hid.png" },
      { name: "썬루프", image: "/Image/options/sunroof.png" },
      { name: "알루미늄휠", image: "/Image/options/wheel.png" },
      { name: "루프랙", image: "/Image/options/roofrack.png" },
      { name: "전동사이드스텝", image: "/Image/options/sidestep.png" },
      { name: "전동접이식미러", image: "/Image/options/foldmirror.png" },
      { name: "하이빔어시스트", image: "/Image/options/hibeam.png" },
      { name: "오토라이트", image: "/Image/options/autolight.png" },
      { name: "주간주행등(DRL)", image: "/Image/options/drl.png" },
      { name: "고스트도어클로징", image: "/Image/options/ghostdoor.png" },
    ],
  },  
  {
    title: "내장 옵션",
    options: [
      { name: "열선시트", image: "/Image/options/heatseat.png" },
      { name: "통풍시트", image: "/Image/options/airseat.png" },
      { name: "가죽시트", image: "/Image/options/seat.png" },
      { name: "자동슬라이딩도어", image: "/Image/options/autodoor.png" },
      { name: "슈퍼비전계기판", image: "/Image/options/supervision.png" },
      { name: "워크인시트", image: "/Image/options/workinswitch.png" },
      { name: "패들시프트", image: "/Image/options/paddleshift.png" },
      { name: "전동햇빛가리개", image: "/Image/options/sunvisor.png" },
      { name: "파워핸들", image: "/Image/options/powerhandle.png" },
      { name: "뒷좌석전동시트", image: "/Image/options/electircseat.png" },
      { name: "하이패스", image: "/Image/options/hipass.png" },
      { name: "통풍시트(뒷좌석)", image: "/Image/options/airseat_rear.png" },
      { name: "핸들리모컨", image: "/Image/options/handleremote.png" },
      { name: "메모리시트", image: "/Image/options/memoryseat.png" },
      { name: "안마시트", image: "/Image/options/relaxseat.png" },
      { name: "엠비언트라이트", image: "/Image/options/ambiantlight.png" }
    ],
  },
  {
    title: "안전 옵션",
    options: [
      { name: "사이드&커튼에어백", image: "/Image/options/sideairback.png" },
      { name: "ABS", image: "/Image/options/ABS.png" },
      { name: "LDWS", image: "/Image/options/LDWS.png" },
      { name: "후방주차센서", image: "/Image/options/rearparkingsensor.png" },
      { name: "후방카메라", image: "/Image/options/rearcamera.png" },
      { name: "ECS", image: "/Image/options/ECS.png" },
      { name: "도난경보기", image: "/Image/options/alarm.png" },
      { name: "전방카메라", image: "/Image/options/frontcamera.png" },
      { name: "어라운드뷰", image: "/Image/options/360view.png" },
      { name: "TCS", image: "/Image/options/TCS.png" },
      { name: "TPMS", image: "/Image/options/TPMS.png" },
      { name: "자동긴급제동(AEB)", image: "/Image/options/AEB.png" },
      { name: "ESC", image: "/Image/options/ESC.png" },
      { name: "전방주차센서", image: "/Image/options/frontparkingsensor.png" },
      { name: "블랙박스", image: "/Image/options/blackbox.png" }
    ],
  },
  {
    title: "편의 / 멀티미디어 옵션",
    options: [
      { name: "스마트키", image: "/Image/options/smartkey.png" },
      { name: "ECM룸미러", image: "/Image/options/ECM.png" },
      { name: "무선도어잠금장치", image: "/Image/options/doorlock.png" },
      { name: "네비게이션(순정)", image: "/Image/options/nav_real.png" },
      { name: "AUX", image: "/Image/options/AUX.png" },
      { name: "파워윈도우", image: "/Image/options/powerwindow.png" },
      { name: "자동도어잠금", image: "/Image/options/autolock.png" },
      { name: "자동주차시스템", image: "/Image/options/autoparking.png" },
      { name: "HUD", image: "/Image/options/HUD.png" },
      { name: "EPB", image: "/Image/options/EPB.png" },
      { name: "크루즈컨트롤", image: "/Image/options/cruise.png" },
      { name: "레인센서와이퍼", image: "/Image/options/rainsensor.png" },
      { name: "네비게이션(비순정)", image: "/Image/options/nav_fake.png" },
      { name: "CD플레이어", image: "/Image/options/cd.png" },
      { name: "핸즈프리", image: "/Image/options/handfree.png" },
      { name: "MP3", image: "/Image/options/MP3.png" },
      { name: "블루투스", image: "/Image/options/bluetooth.png" }
     
    ],
  },
];